quarkus:
  kubernetes:
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
    ingress:
      annotations:
        "cert-manager.io/cluster-issuer": letsencrypt-prod

# Note that the file name must have only alphabetic characters or underscores (_).
  openapi-generator:
    codegen:
      spec:
        api_spec_yaml:
          base-package: org.continuouspoker.player